meta:
  title: Foliensatz
slide:
  loop: false
  math: true
  chart: true
  ui:
    sidebar: true
    vertical: false
    pagination: fraction # bullets | progressbar | fraction
    effect: fade # fade | cube | flip
  code:
    languages: # by https://prismjs.com/
      - java
      - json
    plugins:
      - line-numbers
    theme: default # default | coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight